/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.sgi.telas.view;

import br.ufes.sgi.model.Notificacao;
import br.ufes.sgi.model.Permissao;
import br.ufes.sgi.model.Solicitacao;
import br.ufes.sgi.service.ImagemService;
import br.ufes.sgi.service.NotificacaoService;
import br.ufes.sgi.service.PermissaoService;
import br.ufes.sgi.service.SolicitacaoService;
import br.ufes.sgi.service.UsuarioService;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 55289
 */
public class SetarPermissao extends javax.swing.JFrame {
    
    private SolicitacaoService solicitacaoService;
    private PermissaoService permissaoService;
    private Solicitacao solicitacao;
    private NotificacaoService serviceNotificacao;
    private UsuarioService serviceUsuario;
    private ImagemService imagemService;

    /**
     * Creates new form SetarPermissao
     */
    public SetarPermissao(Solicitacao solicitacao) throws Exception {
        initComponents();
        this.solicitacaoService = new SolicitacaoService();
        this.solicitacao = solicitacao;
        jLabelNome.setText(serviceUsuario.getById(solicitacao.getUsuarioSolicitante().getId()).getNome());
        jLabelImagem.setText(imagemService.getImagemById(solicitacao.getImagem().getId()).getCaminho());
        jTextAreaDescricao.setText(solicitacao.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonCompartilhar = new javax.swing.JRadioButton();
        jRadioButtonVisualizar = new javax.swing.JRadioButton();
        jRadioButtonExcluir = new javax.swing.JRadioButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();

        setTitle("Definir Permissão");

        jRadioButtonCompartilhar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButtonCompartilhar.setText("Compartilhar");
        jRadioButtonCompartilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompartilharActionPerformed(evt);
            }
        });

        jRadioButtonVisualizar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButtonVisualizar.setText("Visualizar");

        jRadioButtonExcluir.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRadioButtonExcluir.setText("Excluir");

        jButtonConfirmar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Usuário:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Imagem:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Permissões:");

        jLabelNome.setText("xxxxxxxx");

        jLabelImagem.setText("xxxxxxxx");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Descrição:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelNome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelImagem))
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCompartilhar)
                    .addComponent(jRadioButtonVisualizar)
                    .addComponent(jRadioButtonExcluir))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelImagem))
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonCompartilhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonExcluir)
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmar)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCompartilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompartilharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCompartilharActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        
        try {
            //pegando a permissao conforme a imagem e usuario solicitante
            Permissao permissao = permissaoService.getPermissao(solicitacao.getImagem().getId(), solicitacao.getUsuarioSolicitante().getId());
            //caso essa permissao já exista, iremos somente edita-la
            if (permissao != null) {
                //setando os dados permissao
                permissao.setCompartilhar(jRadioButtonCompartilhar.isSelected());
                permissao.setExcluir(jRadioButtonExcluir.isSelected());
                permissao.setVisualizar(jRadioButtonVisualizar.isSelected());
                //criando o compartilhamento, ja que foi autorizado
                permissaoService.salvarPermissao(permissao);
            } else {//caso ele não tenha uma permissao no banco

                //ja que o usuario não tem uma permissao, então uma nova permissao é criada
                Permissao newPermissao = new Permissao();
                //setando os dados da permissao
                newPermissao.setUsuario(solicitacao.getUsuarioSolicitante());
                newPermissao.setImagem(solicitacao.getImagem());
                permissao.setCompartilhar(jRadioButtonCompartilhar.isSelected());
                permissao.setExcluir(jRadioButtonExcluir.isSelected());
                permissao.setVisualizar(jRadioButtonVisualizar.isSelected());
                //criando o compartilhamento, ja que foi autorizado
                permissaoService.salvarPermissao(permissao);
            }

            //notificando o usuário que pediu a solicitacao, que ela foi aceita
            serviceNotificacao.salvar(new Notificacao(solicitacao.getUsuarioSolicitante(), "Solicitação:\n" + solicitacao.getDescricao() + "foi recebida e confirmada!"));
            solicitacaoService.excluir(solicitacao.getId());
        } catch (Exception ex) {
            Logger.getLogger(SetarPermissao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JRadioButton jRadioButtonCompartilhar;
    private javax.swing.JRadioButton jRadioButtonExcluir;
    private javax.swing.JRadioButton jRadioButtonVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    // End of variables declaration//GEN-END:variables
}
