/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.sgi.view;

import br.ufes.sgi.model.Imagem;
import br.ufes.sgi.model.Notificacao;
import br.ufes.sgi.model.Permissao;
import br.ufes.sgi.model.Usuario;
import br.ufes.sgi.service.NotificacaoService;
import br.ufes.sgi.service.PermissaoService;
import br.ufes.sgi.service.UsuarioService;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55289
 */
public class CompartilharImagemView extends javax.swing.JFrame {

    private PermissaoService servicePermissao;
    private NotificacaoService serviceNotificacao;
    private UsuarioService serviceUsuario;
    private boolean tipo;
    private Permissao permissao;
    private Imagem img;

    /**
     * Creates new form CompartilharImagem
     */
    public CompartilharImagemView(Permissao permissao, boolean tipo) throws Exception {//pedir permissao
        initComponents();
        this.servicePermissao = new PermissaoService();
        this.tipo = tipo;
        this.permissao = permissao;
        this.serviceUsuario = new UsuarioService();

        if (tipo) {
            jButtonCompartilhar.setVisible(true);
            jButtonPedirPermissao.setVisible(false);
        } else {
            jButtonCompartilhar.setVisible(false);
            jButtonPedirPermissao.setVisible(true);
        }
        preencheTabela();
    }

    public CompartilharImagemView(Imagem im, boolean tipo) throws Exception {//compartilhar imagem
        initComponents();
        this.img = im;
        this.tipo = tipo;
        this.servicePermissao = new PermissaoService();
        this.serviceUsuario = new UsuarioService();

        if (tipo) {
            jButtonCompartilhar.setVisible(true);
            jButtonPedirPermissao.setVisible(false);
        } else {
            jButtonCompartilhar.setVisible(false);
            jButtonPedirPermissao.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCompartilhar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonPedirPermissao = new javax.swing.JButton();

        setTitle("Compartilhar/Gerar Permissao");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonCompartilhar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonCompartilhar.setText("Compartilhar");
        jButtonCompartilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompartilharActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonPedirPermissao.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButtonPedirPermissao.setText("Pedir Permissão");
        jButtonPedirPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedirPermissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPedirPermissao)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonCompartilhar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPedirPermissao)
                    .addComponent(jButtonCompartilhar)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencheTabela() throws Exception {
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        ArrayList<Usuario> usuarios = null;
        if (tipo) {//se for compartilhar, irá listar os usuarios comuns
            usuarios = serviceUsuario.getAllUser();
            for (Usuario users : usuarios) {
                modelo.addRow(new Object[]{users.getId(), users.getNome()});
            }

        } else {// se for pedir permissao, irá listar os adm para o usuario pedir permissao
            usuarios = serviceUsuario.getAllAdm();
            for (Usuario users : usuarios) {
                modelo.addRow(new Object[]{users.getId(), users.getNome()});
            }
        }
    }


    private void jButtonCompartilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompartilharActionPerformed
        int[] selecao = jTable1.getSelectedRows();
        for (int i = 0; i < selecao.length; i++) {//pode compartilhar pra mais de um usuario
            try {
                servicePermissao.gerarCompartilhamento(new Permissao(new Usuario((int) jTable1.getModel().getValueAt(selecao[i], 0)),
                        img, true, false, false));
                serviceNotificacao.salvar(new Notificacao(new Usuario((int) jTable1.getModel().getValueAt(selecao[i], 0)),
                        "Imagem: " + img.getCaminho() + " compartilhada com voce."));
            } catch (Exception ex) {
                Logger.getLogger(CompartilharImagemView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButtonCompartilharActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPedirPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedirPermissaoActionPerformed
        int selecao = jTable1.getSelectedRow();
        try {
            servicePermissao.gerarCompartilhamento(permissao);//gera o compartilhamento para aguardar a permissao
            
            //aqui em notificacao, a gente descreve qual foi o pedido, passando o id da permissao, ai quando o admin abrir o sistema ele vai receber o notificacao
            
            //serviceNotificacao.salvarById(new Notificacao(new Usuario((int) jTable1.getModel().getValueAt(selecao, 0)),
            //       "Imagem: " + imagem.getCaminho() + " gerou um pedido de permissão pra ser visualizada"));
        } catch (Exception ex) {
            Logger.getLogger(CompartilharImagemView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPedirPermissaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCompartilhar;
    private javax.swing.JButton jButtonPedirPermissao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
